### ISSUE TITLE
Sectors do not contain "Undefined", and term "Accessories" is not well defined

### ISSUE THREAD

**Issue by KlausGPaul** [opensupplyhub/api#1]
To be in line with the default behaviour of OSH, the sectors list needs to also contain the term "Undefined". In addition, when migrating from OAR, many apparel product types are called "Accessories", which may be mapped into that sector, so this term needs to be removed and replaced with "Home Accessories".

**Comment by KlausGPaul** [comment]
Data tables were amended.

**Comment by mariel-oar** [comment]
I wouldn't say that all Accessories belong to one type of sector - e.g. there are automotive accessories, home accessories, apparel accessories. The term Accessories may be too broad / undefined to include in our sector list. 

Apparel accessories maybe should map to Apparel, Automotive Accessories to Automotive and Home Accessories to Home Goods
